version: '2'
services:
    maven-image-builder:
        build:
            context: .
        ports:
        - "2222:22"
        container_name: maven-image-builder
        privileged: true
        extra_hosts:
        - "docker-virtual.art.local docker-dev-local2.art.local docker-prod-local2.art.local:192.168.99.100"
